// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PingRequester.Data;

#nullable disable

namespace PingRequester.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("PingRequester.Data.Entities.RequestRunSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("AverageResponseTimeMs")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("End")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ipv4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Lost")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacketSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PingTarget")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Received")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserPreferencesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserPreferencesId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("PingRequester.Data.Entities.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InfiniteLoop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PacketSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PingRequestCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PingTarget")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RefreshRate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StopWhenSuccess")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Preferences");
                });

            modelBuilder.Entity("PingRequester.Data.Entities.RequestRunSession", b =>
                {
                    b.HasOne("PingRequester.Data.Entities.UserPreferences", "UserPreferences")
                        .WithMany("Sessions")
                        .HasForeignKey("UserPreferencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("PingRequester.Data.Entities.UserPreferences", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
